<a href="https://colab.research.google.com/github/jesm-erick/Numpy/blob/main/Sesion1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#importamos la libreria numpy de python
import numpy as  np

In [81]:
#creamos un array de una dimensión
arreglo = np.array([1,2,3,9,8,7])
print(arreglo)
#hacemos referencia
numero_par=arreglo[1] #hacemos referencia al numero 2 que esta en el índice 1
print(numero_par)

[1 2 3 9 8 7]
2


In [16]:
tablero = np.array([[1,2,3],[4,5,6],[7,8,9],[0,-1,-2]])
print(tablero)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 -1 -2]]


In [25]:
#ejemplos de referencia a elementos del arreglo bidimensional
n1 = tablero[0][0]#hacemos referencia al elemento ubicado en la fila 0 y columna 0
print(n1)
n2 = tablero[3][2]#hacemos referencia al elemento ubicado en la fila 3 y columna 2
print(n2)
n3 = tablero[2][2]#hacemos referencia al elemento ubicado en la fila 2 y columna 2
print(n3)
#recordar que los índices de filas y columnas inician en 0 y no en 1

1
-2
9


Propiedades principales de los arreglos

In [26]:
#número de dimensiones, usamos la propiedad "ndim" para obtener
#la dimensión de un arreglo
print(arreglo.ndim)
print(tablero.ndim)

1
2


In [29]:
#propiedad "shape", nos devuelve el número de columnas para un arreglo
#de una sola dimensión y el número de columnas y filas para un arreglo de dos dimensiones
print(arreglo.shape)
print(tablero.shape)

(3,)
(4, 3)


In [32]:
#propiedad "size", nos devuelve el número total de elementos que tiene el arreglo
print(arreglo.size)
print(tablero.size)

3
12


In [41]:
#otras funciones utiles:
tablero_ceros=np.zeros((8,8),int)#creamos un tablero de 8X8 con ceros
#en cada uno de sus elementos
print(tablero_ceros)


tablero_unos=np.ones((8,8),int)#creamos un tablero de 8X8 con valores uno
#en cada uno de sus elementos
print(tablero_unos)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [44]:
#creamos un tablero inicializado en cualquier valor, ejemplo con 22.
tablero_x=np.full((8,8),22,int)
print(tablero_x)

[[22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]
 [22 22 22 22 22 22 22 22]]


In [47]:
#arreglo inicializado con valores aleatorios
tablero_a=np.random.rand(3,3)
print(tablero_a)

[[0.27870904 0.63176177 0.13741564]
 [0.61533379 0.69739961 0.50892351]
 [0.57199643 0.87227405 0.34787479]]


In [77]:
tablero_a2= np.random.randint(1,11,size=(8,8))
print(tablero_a2)

[[ 3  9  6  1  6 10  9  7]
 [ 3  6  5  9  3  4  8  7]
 [ 8  5  4  6  6  7  8  2]
 [ 9  5 10  9  3  1  3  8]
 [ 7  8  1  4  5  6  6  2]
 [ 9  2  5  9  2  6  5  9]
 [ 8  8  6  5  5  9  3  7]
 [ 9  7  5  1 10  4 10  2]]


In [79]:
suma_f = 0
suma_f2 = 0
for i in range (8): #este for dará 8 vueltas o iteraciones
  #print(i)
  suma_f=0
  for j in range (8):
    suma_f = suma_f + tablero_a2[i][j]
  print(f"La suma de la fila {i} es {suma_f}")

La suma de la fila 0 es 51
La suma de la fila 1 es 45
La suma de la fila 2 es 46
La suma de la fila 3 es 48
La suma de la fila 4 es 39
La suma de la fila 5 es 47
La suma de la fila 6 es 51
La suma de la fila 7 es 48


In [88]:
#propiedad "reshape", perimite redimnesionar una matriz o un vector
#siempre y cuando la multipliacción de las filas y columnas de la
#nueva matriz sea igual al número total de elementos de la matriz original.
print(arreglo)
#redimensionamos "arreglo" a una matriz 6x1
nuevo_arreglo = arreglo.reshape((6,1))
print(nuevo_arreglo)

#redimensionamos "arreglo" a una matriz 3x2
nuevo_arreglo1 = arreglo.reshape((3,2))
print(nuevo_arreglo1)


[1 2 3 9 8 7]
[[1]
 [2]
 [3]
 [9]
 [8]
 [7]]
[[1 2]
 [3 9]
 [8 7]]
