<a href="https://colab.research.google.com/github/jesm-erick/Numpy/blob/main/Sesion4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Guía Práctica de NumPy**

**Importar NumPy:**

In [75]:
import numpy as np

**1. Creación de Arrays:**

In [76]:
#Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
array = np.array([2,3,4,5,6])
print(array)

[2 3 4 5 6]


In [77]:
#Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
new_array = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(new_array)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [78]:
#Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
array_zeros = np.zeros([2,4], int)
print(array_zeros)

[[0 0 0 0]
 [0 0 0 0]]


In [79]:
# Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.

array_ones = np.ones([3,2], int)
print(array_ones)

[[1 1]
 [1 1]
 [1 1]]


In [80]:
# Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.

array_random_0_10 = np.random.randint(0,10, size=(4,4))

print(array_random_0_10)

[[5 0 2 4]
 [3 9 7 8]
 [8 3 8 2]
 [2 6 5 8]]


**2. Acceso a Elementos:**

In [81]:
# Accede al tercer elemento del vector creado en el paso 1.
elemento_3 = array[2]

print(elemento_3)

4


In [82]:
#Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.
elemento_2 = new_array[1][1]
print(elemento_2)

8


**3. Propiedades de los Arrays:**

In [83]:
# Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.

print(new_array.ndim)

2


In [84]:
# Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
print(new_array.shape)

(3, 3)


In [21]:
# Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.

print(new_array.size)

9


**4. Operaciones Básicas:**

In [85]:
# Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.

matriz_a = np.random.randint(0,10, size=(2,2))
matriz_b = np.random.randint(0,10, size=(2,2))
suma = matriz_a + matriz_b
print(f"Matriz A: \n {matriz_a}")
print(f"Matriz B: \n {matriz_b}")
print(f"Suma : \n {suma}")

Matriz A: 
 [[6 6]
 [5 7]]
Matriz B: 
 [[0 8]
 [5 3]]
Suma : 
 [[ 6 14]
 [10 10]]


In [86]:
# Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.

matriz_a = np.random.randint(0, 10, size=(3, 2))
matriz_b = np.random.randint(0, 10, size=(2, 3))

producto = np.dot(matriz_a, matriz_b)

print(f"Matriz 3x2: \n{matriz_a}")
print(f"Matriz 2x3: \n{matriz_b}")
print(f"Producto: \n{producto}")


Matriz 3x2: 
[[2 8]
 [9 2]
 [7 3]]
Matriz 2x3: 
[[0 5 6]
 [9 9 7]]
Producto: 
[[72 82 68]
 [18 63 68]
 [27 62 63]]


In [87]:
# Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,
matriz_a = np.random.randint(1, 10, size=(2, 2))
matriz_b = np.random.randint(1, 10, size=(2, 2))

division = matriz_a / matriz_b

print(f"Matriz A: \n {matriz_a}")
print(f"Matriz B: \n {matriz_b}")
print(f"Division : \n {division}")

Matriz A: 
 [[2 9]
 [6 8]]
Matriz B: 
 [[1 7]
 [1 2]]
Division : 
 [[2.         1.28571429]
 [6.         4.        ]]


**5. Manipulación de Arrays:**

In [88]:
# Utiliza la función reshape() para convertir el vector creado en el paso 2 en una matriz de tamaño 2x3.

reshape = new_array.reshape((9,1))
print(reshape)

[[ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [89]:
# Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.

flatten= new_array.flatten()
print(flatten)


[ 4  5  6  7  8  9 10 11 12]


**6. Operaciones Estadísticas:**

In [90]:
# Calcula la suma de todos los elementos de la matriz creada en el paso 2.

sum_of_elements = np.sum(new_array)
print(f"Arreglo: \n {new_array}")
print(f"La suma de todos los elementos es: {sum_of_elements}")


Arreglo: 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
La suma de todos los elementos es: 72


In [91]:
# Calcula la media de cada fila de la matriz creada en el paso 2.

media = np.mean(new_array, axis=1,)
print(f"Arreglo: \n {new_array}")
print(f"La media de cada fila es: {media}")


Arreglo: 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
La media de cada fila es: [ 5.  8. 11.]


**7. Indexación y Rebanado:**

In [92]:
# Imprime la primera fila de la matriz creada en el paso 2.

print(new_array[0])


[4 5 6]


In [64]:
# Imprime las primeras dos columnas de la matriz creada en el paso 2.

print(new_array[:, :2])

[[ 4  5]
 [ 7  8]
 [10 11]]


**8. Ejercicio Adicional:**

In [94]:
# Define una matriz de tamaño 4x4 con valores aleatorios.

matriz =np.random.rand(4,4)
print(matriz)

[[0.73612288 0.44088892 0.04072247 0.53402688]
 [0.65027928 0.39298267 0.59354041 0.91452088]
 [0.4313196  0.61295284 0.20687584 0.33371399]
 [0.29591212 0.65279782 0.12931791 0.08522338]]


In [93]:
# Encuentra el valor máximo y su posición en filas y columnas.
max_value = np.max(matriz)
max_index = np.argmax(matriz)
max_row = max_index // 4
max_col = max_index % 4

# Encuentra el valor mínimo y su posición en filas y columnas.
min_value = np.min(matriz)
min_index = np.argmin(matriz)
min_row = min_index // 4
min_col = min_index % 4

# Imprime los resultados.
print("Matriz:")
print(matriz)
print("\nValor máximo:", max_value)
print("Fila:", max_row, "Columna:", max_col)
print("\nValor mínimo:", min_value)
print("Fila:", min_row, "Columna:", min_col)


Matriz:
[[0.78831868 0.51593728 0.26846669 0.21151564]
 [0.00677973 0.46367112 0.38248523 0.56034837]
 [0.69899324 0.10836226 0.61158789 0.18010783]
 [0.82796825 0.01599738 0.39933679 0.84568685]]

Valor máximo: 0.8456868516968259
Fila: 3 Columna: 3

Valor mínimo: 0.006779729296704118
Fila: 1 Columna: 0
